language: node_js

node_js:
  - '12'

cache: yarn

install:
  - yarn install
  - yarn global add firebase-tools

script:
  - yarn test
  - yarn run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
